<?php $posts = $this->getPosts(); ?>
<?php if(count($posts)): ?>
	<?php foreach ($posts as $post): ?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
		<h3>

			<?php echo Mage::helper('blog')->__('Posted');?>
	        <?php echo $this->__("By");?> <?php echo $post->getUser(); ?> &ndash;
	        <?php echo date('jS F Y', strtotime($post->getCreatedTime())); ?>
	        
	        <?php $postCats = $post->getCats(); ?>
	        <?php if(!empty($postCats)):?>
	            <?php echo Mage::helper('blog')->__(' in');?>
	            <?php foreach($postCats as $title=>$url): ?>
	                <a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
	            <?php endforeach;?> 
	        <?php endif;?>
		</h3>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<a href="<?php echo $post->getAddress(); ?>" class="btn btn-more" >Read More</a>
	<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>

</div>
	<?php endforeach; ?>
<?php else: ?>  
<?php echo Mage::helper('blog')->__('No Posts in this Category.');?>
<?php endif; ?>
<?php $this->getPages(); ?>
